/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.RatView.main;

import java.awt.Color;

/**
 *
 * @author Simon
 */
public class RamseyCalculator extends javax.swing.JDialog {

    /**
     * Creates new form RamseyCalculator
     */
    public RamseyCalculator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wl = new javax.swing.JComboBox();
        pa = new javax.swing.JComboBox();
        ab = new javax.swing.JComboBox();
        cs = new javax.swing.JComboBox();
        ia = new javax.swing.JComboBox();
        tc = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        conclusion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        wl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "% Weight Loss", "0-4%", "5-9%", "10-14%", "15-19%", "20+%" }));

        pa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Physical Appearance", "No apparent alterations", "Lack of grooming and/or alopecia", "Dermatitis, porphyrin, and/or ocular and/or nasal discharge", "Piloerection, antalgic position, and/or severe porphyrin", "Antalgic position and closed eyes" }));

        ab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activity and Behavior", "Normal mobility and aware state", "Reduced mobility but aware and social behavior", "Reduced mobility and isolated behavior but aware", "Mobility significantly reduced and in an unware state", "Does not respond to stimulants" }));

        cs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Clinical Signs", "No signs", "Loose stools and/or hematuria", "Difficulty breathing", "Severe diahrrea", "Difficulty breathing, paleness, convultions, temperature ±3°C normal" }));

        ia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Injury and Autotomy ", "Without injuries ", "Erythema or crusting wounds ", "Dehisencia ", "Digital autotomy ", "Mutilating autotomy" }));

        tc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tumors and Cysts", "Without tumors/cysts", "Subcutaneus tumor/cysts <1cm.", "Tumor/cyst with scab and/or >1cm.", "Tumor/cyst that hinders mobility" }));

        jLabel1.setText("Ramsey Calculator");

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Please fill out all fields and press calculate");

        conclusion.setEditable(false);
        conclusion.setBackground(java.awt.Color.white);
        conclusion.setText("Conclusion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(wl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conclusion))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conclusion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int total = 0;

        total += pa.getSelectedIndex() * 5;
        total += ab.getSelectedIndex() * 5;
        total += cs.getSelectedIndex() * 5;

        total -= 15;

        if (wl.getSelectedIndex() == 2) {
            total += 2;
        } else if (wl.getSelectedIndex() == 3) {
            total += 5;
        } else {
            total += wl.getSelectedIndex() * 5;
            total -= 5;
        }

        if (ia.getSelectedIndex() == 2) {
            total += 2;
        } else {
            total += ia.getSelectedIndex() * 5;
            total -= 5;
        }

        total += tc.getSelectedIndex() * 5;
        if (tc.getSelectedIndex() > 2 || tc.getSelectedIndex() > 2) {
            total += 5;
        }
        total -= 5;

        if (wl.getSelectedIndex() == 0 || pa.getSelectedIndex() == 0 || ab.getSelectedIndex() == 0 || cs.getSelectedIndex() == 0 || ia.getSelectedIndex() == 0 || tc.getSelectedIndex() == 0) {

            conclusion.setBackground(Color.WHITE);
            conclusion.setText("Conclusion");
            jLabel2.setText("Please fill out all fields and press calculate");
        } else {
            jLabel2.setText("Ramsey: " + total);
            if (total < 15) {
                conclusion.setBackground(Color.GREEN);
                conclusion.setText("Animal is healthy, no action requiered");
            } else if (total >= 15 && total < 20) {
                conclusion.setBackground(Color.YELLOW);
                conclusion.setText("Animal should be watched, possible action requiered");
            } else if (total >= 20) {
                conclusion.setBackground(Color.RED);
                conclusion.setText("Immidiate euthanasia");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RamseyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RamseyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RamseyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RamseyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RamseyCalculator dialog = new RamseyCalculator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ab;
    private javax.swing.JTextField conclusion;
    private javax.swing.JComboBox cs;
    private javax.swing.JComboBox ia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox pa;
    private javax.swing.JComboBox tc;
    private javax.swing.JComboBox wl;
    // End of variables declaration//GEN-END:variables
}
